import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useState } from 'react';
import {Card, Button, Container, Row, Col, Text} from '@nextui-org/react';
import Header from '../components/Header';
import Portfolio from '../components/Portfolio';
import Home from '../components/Home';
import Hero from '../components/Hero';
import AboutMe from '../components/AboutMe';
import Resume from '../components/Resume';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

export default function landing () {

  return (
    <div>
      <Head>
        <title>PFH - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <div className={styles.container}>
          <div className={styles.contentwrap}>
            <Header/>
            <AboutMe />
          </div>
          <Footer />
        </div>
      </body>
    </div>
  )
};
