import Head from "next/head";

import Header from "./Header";
import NavBar from "./NavBar";

import navButtons from '../utils/data/navButtons';

import styles from '../styles/Layout.module.scss';

const Layout = props => (
  <div className={styles.Layout}>
    
    <Head>
      <title>PFH - Full Stack Developer</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <NavBar navButtons={navButtons} />
    <div className={styles.Content}>{props.children}</div>
    
  </div>
);

export default Layout;
